# src/phases.py
"""
Enhanced Phase Executor with Deep Legal Training and Dynamic Prompting
All 6 phases with cumulative learning and self-directed investigation
"""

from typing import List, Dict, Any
from datetime import datetime
import json
import logging
import prompts
import utils

logger = logging.getLogger(__name__)


class PhaseExecutor:
    """Executes all 6 phases of the investigation with progressive learning"""
    
    def __init__(self, investigator):
        self.investigator = investigator
        self.api_client = investigator.api_client
        self.knowledge_base = investigator.knowledge_base
        self.document_tracker = investigator.document_tracker
        self.project_root = investigator.project_root
        self.config = investigator.config
        
        # Store phase-specific findings for dynamic prompting
        self.phase_findings = {}
        
        # Store dynamic prompts generated by Claude
        self.dynamic_prompts = {}
    
    async def run_all_phases(self, documents: List[Dict]):
        """Execute all phases sequentially with cumulative learning"""
        
        # PHASE 0A: Deep Legal Training
        print("\n" + "-"*50)
        print("📚 PHASE 0A: Legal Training (Opus 4.1 Mode)")
        await self.phase_0a_legal_training()
        
        # PHASE 0B: Case Context Analysis as Lismore's Counsel
        print("\n" + "-"*50)
        print("📖 PHASE 0B: Case Context Learning (Opus 4.1 Analysis)")
        await self.phase_0b_case_context()
        
        # PHASE 1: Document Landscape with Legal Expertise
        print("\n" + "-"*50)
        print("🎓 PHASE 1: Document Landscape Analysis (Forensic Mode)")
        await self.phase_1_landscape(documents)
        
        # PHASE 2: Pattern Recognition with Dynamic Prompting
        print("\n" + "-"*50)
        print("🔍 PHASE 2: Pattern Recognition (Advanced Detection)")
        await self.phase_2_patterns(documents)
        
        # PHASE 3: Anomaly Detection with Accumulated Knowledge
        print("\n" + "-"*50)
        print("🚨 PHASE 3: Anomaly Detection (Forensic Analysis)")
        await self.phase_3_anomalies(documents)
        
        # PHASE 4: Theory Building with Legal Framework
        print("\n" + "-"*50)
        print("🧩 PHASE 4: Theory Building (Litigation Strategy)")
        await self.phase_4_theories(documents)
        
        # PHASE 5: Evidence Analysis for Trial
        print("\n" + "-"*50)
        print("⚖️ PHASE 5: Evidence Analysis (Trial Preparation)")
        await self.phase_5_evidence(documents)
        
        # PHASE 6: Kill Shot Identification
        print("\n" + "-"*50)
        print("⚔️ PHASE 6: Kill Shot Identification (Opus 4.1 Maximum)")
        await self.phase_6_kill_shots(documents)
    
    async def phase_0a_legal_training(self):
        """
        Phase 0A: Deep legal training to become expert arbitration litigator
        Actually reads and analyses legal documents to build expertise
        """
        legal_dir = self.project_root / "legal_resources"
        
        print("📚 Building deep legal expertise...")
        
        # Load all legal documents
        legal_texts = []
        legal_docs = []
        
        if legal_dir.exists():
            for file in legal_dir.glob("**/*"):
                if file.suffix in ['.txt', '.pdf', '.doc', '.docx']:
                    legal_docs.append({
                        'doc_id': file.stem,
                        'filename': file.name,
                        'path': str(file)
                    })
                    # Try to read text files directly
                    if file.suffix == '.txt':
                        try:
                            with open(file, 'r', encoding='utf-8') as f:
                                content = f.read()
                                legal_texts.append(f"[{file.name}]\n{content[:5000]}")
                        except Exception as e:
                            logger.error(f"Error reading {file}: {e}")
        
        # Get legal training prompt from prompts module
        legal_training_prompt = prompts.get_phase_0a_legal_training_prompt(
            doc_count=len(legal_docs),
            legal_texts=legal_texts[:10]  # First 10 documents
        )
        
        # Send to API for learning
        response = await self.api_client.make_api_call(legal_training_prompt, phase='phase_0a')
        
        # Store comprehensive legal knowledge
        self.knowledge_base['legal_training'] = {
            'expertise_summary': response,
            'documents_studied': len(legal_docs),
            'training_complete': True,
            'specialisations': [
                'LCIA Arbitration',
                'Document Forensics', 
                'Fraud Detection',
                'Cross-Examination',
                'Adverse Inference'
            ],
            'key_precedents': {
                'P&ID': 'Fraud detection methods',
                'Seamus Andrew': 'Failed defence patterns',
                'Document withholding': 'Adverse inference triggers'
            },
            'timestamp': datetime.now().isoformat()
        }
        
        # Store phase findings
        self.phase_findings['phase_0a'] = response
        
        print(f"✅ Legal expertise acquired from {len(legal_docs)} sources")
        self.investigator._save_knowledge_base()
    
    async def phase_0b_case_context(self):
        """
        Phase 0B: Apply legal expertise to case context as Lismore's solicitor
        """
        context_dir = self.project_root / "case_context"
        
        print("🎯 Applying legal expertise to Lismore case...")
        
        # Load case documents
        case_texts = []
        case_docs = []
        
        if context_dir.exists():
            for file in context_dir.glob("**/*"):
                if file.suffix in ['.txt', '.pdf', '.doc', '.docx']:
                    case_docs.append({
                        'doc_id': file.stem,
                        'filename': file.name,
                        'path': str(file)
                    })
                    if file.suffix == '.txt':
                        try:
                            with open(file, 'r', encoding='utf-8') as f:
                                content = f.read()
                                case_texts.append(f"[{file.name}]\n{content[:5000]}")
                        except Exception as e:
                            logger.error(f"Error reading {file}: {e}")
        
        # Get legal expertise from Phase 0A
        legal_expertise = self.knowledge_base.get('legal_training', {}).get('expertise_summary', '')
        
        # Get case context prompt from prompts module
        case_context_prompt = prompts.get_phase_0b_case_context_prompt(
            legal_expertise=legal_expertise[:3000],
            doc_count=len(case_docs),
            case_texts=case_texts[:10]
        )
        
        # Send to API for case analysis
        response = await self.api_client.make_api_call(case_context_prompt, phase='phase_0b')
        
        # Store comprehensive case understanding
        self.knowledge_base['case_context'] = {
            'strategic_analysis': response,
            'case_theory': 'VR controlled everything, knew everything, approved everything',
            'key_vulnerabilities': [
                '51% voting control defeats exclusion',
                'McNaughton warning proves knowledge',
                'Continued participation waives claims',
                'Due diligence failure bars recovery'
            ],
            'evidence_priorities': [
                'Board minutes showing VR votes',
                'VR response to McNaughton',
                'Post-warning approvals',
                'Missing document patterns'
            ],
            'tribunal_strategy': 'Aggressive adverse inference motions',
            'documents_studied': len(case_docs),
            'timestamp': datetime.now().isoformat()
        }
        
        # Store phase findings
        self.phase_findings['phase_0b'] = response
        
        print(f"✅ Case mastery achieved from {len(case_docs)} documents")
        self.investigator._save_knowledge_base()
    
    async def phase_1_landscape(self, documents: List[Dict]):
        """
        Phase 1: Document landscape with full legal/case knowledge applied
        """
        # Get accumulated knowledge
        legal_knowledge = self.knowledge_base.get('legal_training', {}).get('expertise_summary', '')
        case_strategy = self.knowledge_base.get('case_context', {}).get('strategic_analysis', '')
        
        # Get enhanced phase 1 prompt
        base_prompt = prompts.get_phase_1_prompt_enhanced(
            legal_knowledge=legal_knowledge[:2000],
            case_strategy=case_strategy[:2000]
        )
        
        # Build cumulative context
        cumulative_context = self._build_cumulative_context(1)
        
        # Process documents in batches
        batch_size = self.config.get('investigation', {}).get('batch_size', 40)
        batches = utils.batch_documents(documents, batch_size)
        
        all_findings = []
        
        for batch_num, batch in enumerate(batches):
            # Combine prompts
            full_prompt = f"""
            {base_prompt}
            
            {cumulative_context}
            
            Batch {batch_num + 1}/{len(batches)}: Apply Opus 4.1 forensic capabilities.
            """
            
            # Add documents
            formatted_batch = utils.format_batch_with_metadata(batch)
            final_prompt = full_prompt + "\n\nDocuments:\n" + formatted_batch
            
            # Send to API
            response = await self.api_client.make_api_call(final_prompt, phase='phase_1')
            all_findings.append(response)
            
            # Track documents for withholding analysis
            for doc in batch:
                self.document_tracker.analyse_for_withholding(
                    doc.get('text', ''),
                    doc.get('doc_id', 'unknown')
                )
            
            # Update knowledge base
            self._update_knowledge_base('phase_1', response)
        
        # Store all phase findings
        self.phase_findings['phase_1'] = "\n\n".join(all_findings)
        
        # Generate dynamic prompt for next phase
        await self._generate_dynamic_next_phase_prompt(1)
        
        self.investigator.performance_metrics['phases_completed'] += 1
        print("✅ Phase 1 complete: Forensic landscape analysis completed")
    
    async def phase_2_patterns(self, documents: List[Dict]):
        """
        Phase 2: Pattern recognition with dynamic prompting from Phase 1
        """
        # Get base prompt
        base_prompt = prompts.get_phase_2_prompt()
        
        # Add dynamic additions from Phase 1
        dynamic_additions = self.dynamic_prompts.get('phase_2', '')
        
        # Get accumulated knowledge
        legal_knowledge = self.knowledge_base.get('legal_training', {}).get('expertise_summary', '')
        case_strategy = self.knowledge_base.get('case_context', {}).get('strategic_analysis', '')
        
        # Build enhanced prompt
        enhanced_prompt = prompts.get_phase_2_prompt_enhanced(
            base_prompt=base_prompt,
            dynamic_additions=dynamic_additions,
            legal_knowledge=legal_knowledge[:1000],
            case_strategy=case_strategy[:1000]
        )
        
        # Build cumulative context
        cumulative_context = self._build_cumulative_context(2)
        
        # Process batches
        batches = utils.batch_documents(documents, 40)
        all_findings = []
        
        for batch_num, batch in enumerate(batches):
            full_prompt = f"""
            {enhanced_prompt}
            
            {cumulative_context}
            
            Pattern Recognition Batch {batch_num + 1}/{len(batches)}
            """
            
            formatted_batch = utils.format_batch_with_metadata(batch)
            final_prompt = full_prompt + "\n\nDocuments:\n" + formatted_batch
            
            response = await self.api_client.make_api_call(final_prompt, phase='phase_2')
            all_findings.append(response)
            
            self._update_knowledge_base('phase_2', response)
        
        # Store findings
        self.phase_findings['phase_2'] = "\n\n".join(all_findings)
        
        # Generate dynamic prompt for next phase
        await self._generate_dynamic_next_phase_prompt(2)
        
        self.investigator.performance_metrics['phases_completed'] += 1
        print("✅ Phase 2 complete: Advanced patterns identified")
    
    async def phase_3_anomalies(self, documents: List[Dict]):
        """
        Phase 3: Anomaly detection with accumulated knowledge
        """
        # Similar structure to phase_2
        base_prompt = prompts.get_phase_3_prompt()
        dynamic_additions = self.dynamic_prompts.get('phase_3', '')
        
        enhanced_prompt = prompts.get_phase_3_prompt_enhanced(
            base_prompt=base_prompt,
            dynamic_additions=dynamic_additions,
            accumulated_knowledge=self._get_accumulated_knowledge()
        )
        
        cumulative_context = self._build_cumulative_context(3)
        batches = utils.batch_documents(documents, 40)
        all_findings = []
        
        for batch_num, batch in enumerate(batches):
            full_prompt = f"""
            {enhanced_prompt}
            
            {cumulative_context}
            
            Anomaly Detection Batch {batch_num + 1}/{len(batches)}
            """
            
            formatted_batch = utils.format_batch_with_metadata(batch)
            final_prompt = full_prompt + "\n\nDocuments:\n" + formatted_batch
            
            response = await self.api_client.make_api_call(final_prompt, phase='phase_3')
            all_findings.append(response)
            
            self._update_knowledge_base('phase_3', response)
        
        self.phase_findings['phase_3'] = "\n\n".join(all_findings)
        await self._generate_dynamic_next_phase_prompt(3)
        
        self.investigator.performance_metrics['phases_completed'] += 1
        print("✅ Phase 3 complete: Forensic anomalies catalogued")
    
    async def phase_4_theories(self, documents: List[Dict]):
        """
        Phase 4: Theory building with legal framework
        """
        base_prompt = prompts.get_phase_4_prompt()
        dynamic_additions = self.dynamic_prompts.get('phase_4', '')
        
        enhanced_prompt = prompts.get_phase_4_prompt_enhanced(
            base_prompt=base_prompt,
            dynamic_additions=dynamic_additions,
            accumulated_knowledge=self._get_accumulated_knowledge()
        )
        
        cumulative_context = self._build_cumulative_context(4)
        batches = utils.batch_documents(documents, 40)
        all_findings = []
        
        for batch_num, batch in enumerate(batches):
            full_prompt = f"""
            {enhanced_prompt}
            
            {cumulative_context}
            
            Theory Building Batch {batch_num + 1}/{len(batches)}
            """
            
            formatted_batch = utils.format_batch_with_metadata(batch)
            final_prompt = full_prompt + "\n\nDocuments:\n" + formatted_batch
            
            response = await self.api_client.make_api_call(final_prompt, phase='phase_4')
            all_findings.append(response)
            
            self._update_knowledge_base('phase_4', response)
        
        self.phase_findings['phase_4'] = "\n\n".join(all_findings)
        await self._generate_dynamic_next_phase_prompt(4)
        
        self.investigator.performance_metrics['phases_completed'] += 1
        print("✅ Phase 4 complete: Litigation theories constructed")
    
    async def phase_5_evidence(self, documents: List[Dict]):
        """
        Phase 5: Evidence analysis for trial preparation
        """
        base_prompt = prompts.get_phase_5_prompt()
        dynamic_additions = self.dynamic_prompts.get('phase_5', '')
        
        enhanced_prompt = prompts.get_phase_5_prompt_enhanced(
            base_prompt=base_prompt,
            dynamic_additions=dynamic_additions,
            accumulated_knowledge=self._get_accumulated_knowledge()
        )
        
        cumulative_context = self._build_cumulative_context(5)
        batches = utils.batch_documents(documents, 40)
        all_findings = []
        
        for batch_num, batch in enumerate(batches):
            full_prompt = f"""
            {enhanced_prompt}
            
            {cumulative_context}
            
            Evidence Analysis Batch {batch_num + 1}/{len(batches)}
            """
            
            formatted_batch = utils.format_batch_with_metadata(batch)
            final_prompt = full_prompt + "\n\nDocuments:\n" + formatted_batch
            
            response = await self.api_client.make_api_call(final_prompt, phase='phase_5')
            all_findings.append(response)
            
            self._update_knowledge_base('phase_5', response)
        
        self.phase_findings['phase_5'] = "\n\n".join(all_findings)
        await self._generate_dynamic_next_phase_prompt(5)
        
        self.investigator.performance_metrics['phases_completed'] += 1
        print("✅ Phase 5 complete: Trial evidence prepared")
    
    async def phase_6_kill_shots(self, documents: List[Dict]):
        """
        Phase 6: Kill shot identification with maximum force
        """
        base_prompt = prompts.get_phase_6_prompt()
        dynamic_additions = self.dynamic_prompts.get('phase_6', '')
        
        # This phase gets ALL accumulated knowledge
        full_knowledge = {
            'legal_expertise': self.knowledge_base.get('legal_training', {}),
            'case_strategy': self.knowledge_base.get('case_context', {}),
            'all_findings': self.phase_findings,
            'patterns': self.knowledge_base.get('patterns', {}),
            'anomalies': self.knowledge_base.get('anomalies', {}),
            'theories': self.knowledge_base.get('theories', {})
        }
        
        enhanced_prompt = prompts.get_phase_6_prompt_enhanced(
            base_prompt=base_prompt,
            dynamic_additions=dynamic_additions,
            full_knowledge=json.dumps(full_knowledge, indent=2)[:5000]
        )
        
        cumulative_context = self._build_cumulative_context(6)
        batches = utils.batch_documents(documents, 40)
        all_kill_shots = []
        
        for batch_num, batch in enumerate(batches):
            full_prompt = f"""
            {enhanced_prompt}
            
            {cumulative_context}
            
            Kill Shot Hunt - Batch {batch_num + 1}/{len(batches)}
            OPUS 4.1 MAXIMUM MODE ACTIVATED
            """
            
            formatted_batch = utils.format_batch_with_metadata(batch)
            final_prompt = full_prompt + "\n\nDocuments:\n" + formatted_batch
            
            response = await self.api_client.make_api_call(final_prompt, phase='phase_6')
            all_kill_shots.append(response)
            
            self._update_knowledge_base('phase_6', response)
            
            # Correlate kill shots across batches
            await self._correlate_kill_shots_across_batches(response, batch_num)
        
        # Final ranking
        await self._rank_kill_shots_for_tribunal_impact(all_kill_shots)
        
        # Generate adverse inference report
        adverse_inference_report = self.document_tracker.generate_adverse_inference_report()
        self.knowledge_base['missing_docs']['adverse_inference_opportunities'] = adverse_inference_report
        
        self.phase_findings['phase_6'] = "\n\n".join(all_kill_shots)
        
        self.investigator.performance_metrics['phases_completed'] += 1
        print("✅ Phase 6 complete: Kill shots locked and loaded")
    
    async def _generate_dynamic_next_phase_prompt(self, completed_phase: int):
        """
        Claude generates its own investigation strategy for the next phase
        """
        if completed_phase >= 6:
            return  # No next phase after 6
        
        # Get findings from completed phase
        phase_findings = self.phase_findings.get(f'phase_{completed_phase}', '')
        
        # Get prompt for dynamic generation
        dynamic_prompt = prompts.get_dynamic_phase_prompt(
            completed_phase=completed_phase,
            phase_findings=phase_findings[:3000],
            accumulated_knowledge=self._get_accumulated_knowledge()[:2000]
        )
        
        # Get Claude's self-generated investigation instructions
        response = await self.api_client.make_api_call(
            dynamic_prompt, 
            phase=f'dynamic_{completed_phase}'
        )
        
        # Store for next phase
        self.dynamic_prompts[f'phase_{completed_phase + 1}'] = response
        
        logger.info(f"Generated dynamic prompt for Phase {completed_phase + 1}")
    
    async def _correlate_kill_shots_across_batches(self, findings: str, batch_num: int):
        """
        Correlate kill shots across all batches
        """
        previous_kill_shots = json.dumps(
            self.knowledge_base.get('kill_shots', {}), 
            indent=2
        )[:2000]
        
        correlation_prompt = prompts.get_correlation_prompt(
            batch_num=batch_num,
            current_findings=findings[:2000],
            previous_kill_shots=previous_kill_shots
        )
        
        response = await self.api_client.make_api_call(
            correlation_prompt, 
            phase='correlation'
        )
        
        # Store correlation findings
        if 'forensic_findings' not in self.investigator.investigation_memory:
            self.investigator.investigation_memory['forensic_findings'] = []
        
        self.investigator.investigation_memory['forensic_findings'].append({
            'batch': batch_num,
            'correlations': response,
            'timestamp': datetime.now().isoformat()
        })
    
    async def _rank_kill_shots_for_tribunal_impact(self, all_kill_shots: List[str]):
        """
        Final ranking for maximum tribunal impact
        """
        ranking_prompt = prompts.get_final_ranking_prompt(
            all_kill_shots=str(all_kill_shots)[:12000]
        )
        
        response = await self.api_client.make_api_call(
            ranking_prompt, 
            phase='final_ranking'
        )
        
        # Store final ranking
        if 'kill_shots' not in self.investigator.investigation_memory:
            self.investigator.investigation_memory['kill_shots'] = []
        
        self.investigator.investigation_memory['kill_shots'].append({
            'final_ranking': response,
            'timestamp': datetime.now().isoformat(),
            'model': 'opus_4.1_final'
        })
        
        # Save the final ranking
        output_file = self.project_root / "outputs" / "00_OPUS_41_FINAL_KILL_SHOT_RANKING.md"
        output_file.parent.mkdir(parents=True, exist_ok=True)
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f"# OPUS 4.1 FINAL KILL SHOT RANKING\n\n{response}")
        
        print(f"✅ Final Kill Shot Ranking saved to: {output_file}")
    
    def _build_cumulative_context(self, phase: int) -> str:
        """
        Build context with all accumulated knowledge
        """
        context = "OPUS 4.1 ACCUMULATED INTELLIGENCE:\n\n"
        
        # Add legal training
        if self.knowledge_base.get('legal_training'):
            context += "Legal Framework Mastery:\n"
            context += f"{json.dumps(self.knowledge_base['legal_training'], indent=2)[:1000]}\n\n"
        
        # Add case context
        if self.knowledge_base.get('case_context'):
            context += "Case Intelligence:\n"
            context += f"{json.dumps(self.knowledge_base['case_context'], indent=2)[:1000]}\n\n"
        
        # Add previous phase findings
        for i in range(1, phase):
            if f'phase_{i}' in self.phase_findings:
                context += f"Phase {i} Findings:\n"
                context += f"{self.phase_findings[f'phase_{i}'][:500]}\n\n"
        
        return context[:5000]  # Limit total context size
    
    def _update_knowledge_base(self, phase: str, findings: str):
        """
        Update knowledge base with phase findings
        """
        # Store raw findings
        if phase not in self.knowledge_base:
            self.knowledge_base[phase] = []
        
        self.knowledge_base[phase].append({
            'findings': findings[:2000],  # Store sample
            'timestamp': datetime.now().isoformat()
        })
        
        # Save to disk
        self.investigator._save_knowledge_base()
    
    def _get_accumulated_knowledge(self) -> str:
        """
        Get summary of all accumulated knowledge
        """
        knowledge = {
            'legal_expertise': self.knowledge_base.get('legal_training', {}).get('expertise_summary', '')[:500],
            'case_strategy': self.knowledge_base.get('case_context', {}).get('strategic_analysis', '')[:500],
            'patterns_found': len(self.knowledge_base.get('patterns', {}).get('control_patterns', [])),
            'anomalies_detected': len(self.knowledge_base.get('anomalies', {})),
            'theories_developed': len(self.knowledge_base.get('theories', {}))
        }
        
        return json.dumps(knowledge, indent=2)